before:
  hooks:
    - make clean proto vendor
builds:
  - main: ./cmd/dummy/main.go
    binary: dag1-dummy
    ldflags:
      - -linkmode external -extldflags -static -s -w
      - -X github.com/SamuelMarks/dag1/src/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    # hooks:
    #   pre: make clean proto vendor
  - main: ./cmd/dummy_client/main.go
    binary: dag1-dummy-client
    ldflags:
      - -linkmode external -extldflags -static -s -w
      - -X github.com/SamuelMarks/dag1/src/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/lachesis/main.go
    binary: dag1
    ldflags:
      - -linkmode external -extldflags -static -s -w
      - -X github.com/SamuelMarks/dag1/src/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/lachesis/main_profile.go
    binary: dag1-with-profiler
    ldflags:
      - -linkmode external -extldflags -static -s -w
      - -X github.com/SamuelMarks/dag1/src/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/network/main.go
    binary: dag1-network
    ldflags:
      - -linkmode external -extldflags -static -s -w
      - -X github.com/SamuelMarks/dag1/src/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux

  vendor: Fanton Foundation
  homepage: https://fantom.foundation
  maintainer: Samuel Marks <samuel@fantom.foundation>
  description: BFT Consensus platform for distributed applications.
  license: MIT

  formats:
    - deb
    - rpm

  empty_folders:
    - /var/log/dag1

  files:
    "scripts/daemon/dag1.service": "/lib/systemd/system/dag1.service"

  # scripts:
  #   preinstall: "scripts/preinstall.bash"
